### ISSUE TITLE
The link to "Documentation can be found here." is broken

### ISSUE THREAD

**Issue by williamgoodhew** [dotintent/react-native-ble-plx#885] opened 2021-07-20 11:40 UTC
The link on the homepage to Documentation can be found here is broken. Please could you let me know where I find the latest documentation.

Thanks

**Comment by gretzky** [comment] 2021-07-20 12:19
Duplicate of #882  #867 #866

**Comment by mciechanowicz** [comment] 2021-12-07 15:47
Hi,

This is actual link to documentation: [docs](https://dotintent.github.io/react-native-ble-plx/)

**Closed by mciechanowicz** 2021-12-07 15:47 UTC
