### ISSUE TITLE
How to pairing with pin auto 

### ISSUE THREAD

**Issue by ballza95** [dotintent/react-native-ble-plx#911] opened 2021-10-19 03:13 UTC
I'm need pairing device with pin auto 

Is there any way to suggest, thank you

**Comment by mciechanowicz** [comment] 2022-01-13 12:26
Hi.
I think this is not the scope of that library. Duplicate of: [auto pairing](https://github.com/dotintent/react-native-ble-plx/issues/855) please check that issue.

**Closed by mciechanowicz** 2022-01-13 12:26 UTC
Labels: question
