### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zumi2013** [dotintent/react-native-ble-plx#914] opened 2021-10-25 13:46 UTC
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question

Please describe the question.

**Comment by mciechanowicz** [comment] 2021-12-07 12:15
Hi @zumi2013

This is React Native Bluetooth Low Energy library used with React Native projects.

If you want to use this library or see how it works you must have your react-native project.
To create a new RN project you can use this documentation: https://reactnative.dev/docs/getting-started

Then, to add the react-native-ble-plx library to your project, use the library documentation, specifically the section from this link: [installation & configuration](https://github.com/dotintent/react-native-ble-plx#configuration--installation)

To use the library you can use the quick introduction: [Quick introduction can be found here](https://github.com/dotintent/react-native-ble-plx/blob/master/INTRO.md)
or read the documentation: [Documentation can be found here](https://dotintent.github.io/react-native-ble-plx/)

I hope that I helped you! 😉

**Comment by mciechanowicz** [comment] 2022-01-13 12:21
I think the issue is out of the scope of this library so I'm gonna close it. If you have any other questions please open a new one.

**Closed by mciechanowicz** 2022-01-13 12:21 UTC
Labels: question
