### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zumi2013** [dotintent/react-native-ble-plx#915] opened 2021-10-26 05:29 UTC
Hi sir ,how to run this program [https://github.com/dotintent/react-native-ble-plx/blob/master/docs/README_V1.md](url)
I downloaded the above project from github.
i didn't able to run this program. I got this error image:https://ibb.co/dg1N7Nj

Error program: https://drive.google.com/file/d/1fyktjfxM6f4GcjRKzaK1ZfglBmpeeOI-/view?usp=sharing

![2021-10-25_190317](https://user-images.githubusercontent.com/93113240/138707855-e6c73080-ee18-4377-84f9-de9330ea9613.png)

**Comment by mciechanowicz** [comment] 2021-12-07 12:01
I am closing this one because this is a duplicate of this issue: https://github.com/dotintent/react-native-ble-plx/issues/914

**Closed by mciechanowicz** 2021-12-07 12:01 UTC
Labels: question
